version: '2.4'

services:
  api-jwt:
    container_name: api-jwt
    image: martinhernandez/api-jwt
    build:
      context: .
      target: dev
    ports:
      - '51400:51400'
      - '9229:9229'
    volumes:
      - .:/usr/src/ilove2code/app:delegated
      - /usr/src/ilove2code/app/node_modules
    env_file:
      - .env
    healthcheck:
      test: 'curl --fail http://localhost:51400/welcome || exit 1'
      retries: 0

  reverse-proxy:
    image: nginx:1.19.10-alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
    depends_on:
      api-jwt:
        condition: service_healthy
